# http://vsftpd.beasts.org/vsftpd_conf.html

# Configuració FTP vulnerable 

listen=YES
listen_ipv6=NO

# AUTENTICACIÓ OBLIGATORIA
anonymous_enable=NO
local_enable=YES
write_enable=NO

local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

# CHROOT per a l'usuari
chroot_local_user=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
allow_writeable_chroot=YES

# PASV per a connexions modernes
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pasv_address=

# BANNER per donar una pista del nom d'usuari
ftpd_banner= "[L'usuari magnus es un gran fan dels escacs]"