# http://vsftpd.beasts.org/vsftpd_conf.html

# Configuració FTP vulnerable per al lab AprenCiber

listen=YES
listen_ipv6=NO

# Accés anònim activat
anonymous_enable=YES
anon_root=/var/ftp
no_anon_password=YES
anon_upload_enable=NO

# Usuaris locals activats
local_enable=YES
write_enable=NO
local_umask=022

# Logs i configuració bàsica
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

# Banner extern multilínia
banner_file=/etc/vsftpd.banner

# Chroot per a usuaris locals
chroot_local_user=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
allow_writeable_chroot=YES

# Mode passiu per Docker
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009

seccomp_sandbox=NO