"""refactor_lab_instance_json_columns

Revision ID: 2d60669d3652
Revises: 97dd567dc828
Create Date: 2026-04-25 11:06:20.917236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d60669d3652'
down_revision: Union[str, Sequence[str], None] = '97dd567dc828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_instances', sa.Column('containers_info', sa.Text(), nullable=True))
    op.add_column('lab_instances', sa.Column('networks_info', sa.Text(), nullable=True))
    op.drop_column('lab_instances', 'attacker_container_name')
    op.drop_column('lab_instances', 'network_name')
    op.drop_column('lab_instances', 'vulnerable_container_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_instances', sa.Column('vulnerable_container_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('lab_instances', sa.Column('network_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('lab_instances', sa.Column('attacker_container_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('lab_instances', 'networks_info')
    op.drop_column('lab_instances', 'containers_info')
    # ### end Alembic commands ###
