# type: ignore
"""initial schema

Revision ID: 97dd567dc828
Revises:
Create Date: 2026-04-19 18:04:40.694804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97dd567dc828"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_email"), "profiles", ["email"], unique=True)
    op.create_table(
        "scenarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.String(length=50), nullable=False),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("yaml_path", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenarios_slug"), "scenarios", ["slug"], unique=True)
    op.create_table(
        "lab_instances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("network_name", sa.String(length=255), nullable=True),
        sa.Column("attacker_container_name", sa.String(length=255), nullable=True),
        sa.Column("vulnerable_container_name", sa.String(length=255), nullable=True),
        sa.Column("terminal_url", sa.Text(), nullable=True),
        sa.Column("flag_value", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lab_instances_scenario_id"),
        "lab_instances",
        ["scenario_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lab_instances_user_id"), "lab_instances", ["user_id"], unique=False
    )
    op.create_table(
        "user_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("best_time_seconds", sa.Integer(), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_progress_scenario_id"),
        "user_progress",
        ["scenario_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_progress_user_id"), "user_progress", ["user_id"], unique=False
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("lab_instance_id", sa.Integer(), nullable=False),
        sa.Column("submitted_flag", sa.String(length=255), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lab_instance_id"],
            ["lab_instances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submissions_lab_instance_id"),
        "submissions",
        ["lab_instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_scenario_id"), "submissions", ["scenario_id"], unique=False
    )
    op.create_index(
        op.f("ix_submissions_user_id"), "submissions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_user_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_scenario_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_lab_instance_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_user_progress_user_id"), table_name="user_progress")
    op.drop_index(op.f("ix_user_progress_scenario_id"), table_name="user_progress")
    op.drop_table("user_progress")
    op.drop_index(op.f("ix_lab_instances_user_id"), table_name="lab_instances")
    op.drop_index(op.f("ix_lab_instances_scenario_id"), table_name="lab_instances")
    op.drop_table("lab_instances")
    op.drop_index(op.f("ix_scenarios_slug"), table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_index(op.f("ix_profiles_email"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
