"""add_terminal_pid_to_lab_instance

Revision ID: f22a58ed7805
Revises: ca4c03fe8e21
Create Date: 2026-04-27 09:06:05.510612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f22a58ed7805'
down_revision: Union[str, Sequence[str], None] = 'ca4c03fe8e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_instances', sa.Column('terminal_pid', sa.Integer(), nullable=True))
    op.alter_column('lab_instances', 'containers_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('lab_instances', 'networks_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_instances', 'networks_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('lab_instances', 'containers_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('lab_instances', 'terminal_pid')
    # ### end Alembic commands ###
